### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Aces-and-Jacks** [7777777-4547/Glowing#1]
I don't know if it has something to do with the mod this pack uses or if the mod/resource pack conflicts with another mod/resource pack but this resource pack causes a memory leak each time I open Minecraft

**Comment by Aces-and-Jacks** [comment]
doesn't do it anymore...?

**Comment by 7777777-4547** [comment]
Eh, sorry to reply to you now, I think it should be the mods' problem.(Because I don't think a resourcepack can do it.)
