### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by massimopavoni** [7777777-4547/Glowing#3]
I am trying to make this nice resource pack work with the latest Fabulously Optimized modpack, but this is the overall maximum I can get, and it's strange that these glitches continue to appear.

![2023-11-14_04 26 54](https://github.com/7777777-4547/Glowing/assets/31775087/c3128e7f-c19a-4266-8cff-a7ffa69b22e3)

On top of the modpack, there are a couple datapacks on the server from vanillatweaks (nothing graphical related to ores though) and a resource pack from vanillatweaks again (only things on my mind that could modify the ores are the uniform ores and the alternate block destruction). Added mods I have: do a barrel roll, better f3, fabric api, and I'm pretty sure everything else is just from the modpack.
I'm sorry if the issue is not well filed, I will update with more information if needed.

**Comment by 7777777-4547** [comment]
Because of [this](https://github.com/PepperCode1/Continuity/issues/292).

**Comment by 7777777-4547** [comment]
It seems fixed on [Embeddium](https://modrinth.com/mod/embeddium).
Try to test it.
